### ISSUE TITLE
Need to include arm-linux-gnueabihf on ModulePath?

### ISSUE THREAD

**Issue by bnewbold** [xobs/xorg-novena#2]
I had trouble getting the armada driver to work on my mainboard (with an external display) without adding the following section to 60-novena.conf:

```
Section "Files"
        ModulePath "/usr/lib/xorg/modules/"
        ModulePath "/usr/lib/arm-linux-gnueabihf/xorg/modules/"
EndSection
```

I'm not sure if i'm missing some other package that would have set this variable or what; this could entirely just be a quirk with my system.

**Comment by xobs** [comment]
The ModulePath was updated, as per your suggestion, in commit fde83c7c75b2e3f57c6e9f528a96a9a48a956859
